### PR TITLE
Hide button

### LINKED ISSUE #10: Remove Notion Brand from public pages
I wish there was a feature to remove the 'Try Notion' brand in the top corner of the website so that the website looks cleaner.

### PR DESCRIPTION
**Pull request by omarcostahamido**
- this fixes #10

### CODE REVIEW

**Comment by hosso** [comment]
Sorry for my late response. It's a great feature, and I've merged it.

**Comment by omarcostahamido** [comment]
Thx for merging.
Btw, will you be opening github sponsorships sometime soon?
I never tried it, but I would like to try sponsoring someone like you.

**Comment by hosso** [comment]
I haven't thought about it at the moment, but I'd like to try it sometime.

**Comment by omarcostahamido** [comment]
Did you come up with all this code on your own, or are there any sources that I might look into here on github and perhaps also sponsor? Thank you for your help.

**Pull request merged**
